const ERROR = "Error";
const OK = "OK";
const ERROR_INVALID_TOKEN = "Invalid token";
const ERROR_UINFIN_NOT_FOUND = "Uinfin not found";
const ERROR_PERSON_DATA_NOT_FOUND = "Person data not found";
const ERROR_INVALID_DATA_OR_SIGNATURE = "Invalid data or signature for person data";
const ERROR_CONFIGURATION_CLIENT_PRIVATE_KEY_NOT_FOUND = 'Private key not found';
const ERROR_CONFIGURATION_CLIENT_ID_NOT_FOUND = 'Client id not found';
const ERROR_CONFIGURATION_CLIENT_SECRET_NOT_FOUND = 'Client secret not found';
const ERROR_CONFIGURATION_REDIRECT_URL_NOT_FOUND = 'Redirect URL not found';
const ERROR_CONFIGURATION_TOKEN_URL_NOT_FOUND = "Token URL not found";
const ERROR_CONFIGURATION_PERSON_URL_NOT_FOUND = "Person URL not found";
const ERROR_ENABLE_JWE_FLAG_NOT_FOUND = "ENABLE_JWE flag not found";
const ERROR_INVALID_ENABLE_JWE_FLAG = "Invalid value for ENABLE_JWE flag";
const ERROR_ENABLE_JWS_FLAG_NOT_FOUND = "Enable JWS flag not found";
const ERROR_INVALID_ENABLE_JWS_FLAG = "Invalid value for ENABLE_JWS flag";
const ERROR_CONFIGURATION_SCOPE_NOT_FOUND = "Scope not found";
const ERROR_CONFIGURATION_PROXY_TOKEN_URL_NOT_FOUND = "Proxy Token URL not found";
const ERROR_CONFIGURATION_PROXY_PERSON_URL_NOT_FOUND = "Proxy Person URL not found";
const ERROR_UNKNOWN_AUTH_LEVEL = "Unknown Auth Level";
const ERROR_UNKNOWN_NOT_INIT = "Configurations not initialized";
const ERROR_GENERATE_CLIENT_ASSERTION = "Error generating client assertion";
const ERROR_GENERATE_DPOP = "Error generating dpop token";
const ERROR_VERIFY_JWS = "Error with verifying JWS";
const ERROR_DECRYPT_JWE = "Error with decrypting JWE";

const ENVIRONMENT = {
    SANDBOX: "SANDBOX",
    TEST: "TEST",
    PROD: "PROD"
};

const HTTP_METHOD = {
    GET: "GET",
    POST: "POST"
};

module.exports = {
    ERROR: ERROR,
    OK: OK,
    ENVIRONMENT: ENVIRONMENT,
    HTTP_METHOD: HTTP_METHOD,
    ERROR_INVALID_TOKEN: ERROR_INVALID_TOKEN,
    ERROR_UINFIN_NOT_FOUND: ERROR_UINFIN_NOT_FOUND,
    ERROR_PERSON_DATA_NOT_FOUND: ERROR_PERSON_DATA_NOT_FOUND,
    ERROR_INVALID_DATA_OR_SIGNATURE: ERROR_INVALID_DATA_OR_SIGNATURE,
    ERROR_CONFIGURATION_CLIENT_PRIVATE_KEY_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_ID_NOT_FOUND,
    ERROR_CONFIGURATION_CLIENT_SECRET_NOT_FOUND,
    ERROR_CONFIGURATION_REDIRECT_URL_NOT_FOUND,
    ERROR_CONFIGURATION_TOKEN_URL_NOT_FOUND,
    ERROR_CONFIGURATION_PERSON_URL_NOT_FOUND,
    ERROR_ENABLE_JWE_FLAG_NOT_FOUND,
    ERROR_INVALID_ENABLE_JWE_FLAG,
    ERROR_ENABLE_JWS_FLAG_NOT_FOUND,
    ERROR_INVALID_ENABLE_JWS_FLAG,
    ERROR_CONFIGURATION_SCOPE_NOT_FOUND,
    ERROR_CONFIGURATION_PROXY_TOKEN_URL_NOT_FOUND,
    ERROR_CONFIGURATION_PROXY_PERSON_URL_NOT_FOUND,
    ERROR_UNKNOWN_AUTH_LEVEL,
    ERROR_UNKNOWN_NOT_INIT,
    ERROR_GENERATE_CLIENT_ASSERTION,
    ERROR_GENERATE_DPOP,
    ERROR_VERIFY_JWS,
    ERROR_DECRYPT_JWE
};